'''
@author: YM, JZ, AJH
@date: originally 4-23-13, with subsequent edits

@note: Putting Part 1 to work
'''


def play_with_part1():

    DNA_string = "ATTTGTATGTTCGGCTAACTTCTACCCATCCCCCGAAGTTTAGCAGGTCGTGAGGTGTCATGGAGGCTCTCGTTCATCCCGTGGGACATCAAGCTTCGCCTTGATAAAGCACCCCGCTCGGGTGTAGCAGAGAAGACGCCTACTGAATTGTGCGATCCCTCCACCTCAGCTAAGGTAGCTACCAATATTTAGTTTTTTAGCCTTGCGACAGACCTCCTACTTAGATTGCCACGCATTGAGCTAGCGAGTCAGCGATAAGCATGACGCGCTTTCAAGCGTCGCGAGTATGTGAACCAAGGCTCCGGACAGGACTATATACTTGGGTTTGATCTCGCCCCGACAACTGCAAACCTCAACATTTATAGATTATAAGGTTAGCCGAAATTGCACGTGGTGGCGCCCGCCGACTGCTCCCCGAGTGTGGCTCTTTGATCTGACAACGCGCGACCTCCATCGCGGCCGATTGTTTCTGCGGACCATGTCGTCCTCATAGTTTGGGCATGTTTCCGTTGTAGGAGTGAAGCCACTTAGCTTTGCGCCGTAGTCCCAATGAAAAACCTATGGACTTTGTTTTGGGTAGCATCAGGAATCTGAACCCTGTGAATGTGGGGGTCGCGCGCATAGACCTTTATCTCCGGTTCAAGTTAGGCATGAGGCTGCATGCTACGTTGTCACACCTACACTGCTCGAAGTAAATATGGGAAGCGCGCGGCCTGGCCCGAGGCGTTCCGCGCCGCCACGTGTTCGTTAACTGTTGATTGGTGGCACATAAGCAATACCGTAGTCCCTCAAATTCAGCTCTGTTATCTCGAGCGTTATGTGTCAAATGGCGTAGAACGGGATTGACTGTTTGACACTAGCTGGTGTTCGGTTCGGTAACGGAGAATCTGTGGGGCTATGTCACTAATACTTTCGAAACGCCCCGTACCGATGCTGAACAAGTCGATGCAGGCTCCCGTCTTTGAATAGGGGTAAACATACAAGTCGATAGAAGATGGGT"

    # 1. Write a function called comp which returns the complement of
    #    a single deoxyribonucleotide, e.g. comp('A') -> 'T'

    # 2. Use the comp function and a list comprehension to get the reverse
    #    complement of DNA_string

    # 3. Write a function called purPyrCount which takes a string of DNA and
    #    returns a 2-tuple containing the number of purines (A,G) and the number of
    #    pyrimidines (C,T) in the string
    #    e.g. DNAseq = 'CTAGAGACT'
    #         purPyrCount(DNAseq) -> (5,4)

    # 4. Write a function called motifCount which returns the number of instances
    #    of a motif in a string of DNA
    #    e.g. DNAseq = 'CTAGAGACT'
    #         motifCount(DNAseq,'AGA') -> 2


if __name__ == '__main__':
    play_with_part1()
